### ISSUE TITLE
Log firing before socket setup

### ISSUE THREAD

**Issue by wannabeCitizen** [sikuli/domout#4]
@ianks @develra 

I was messing around with the basic functionality of domout.log in the file domout.js.  I have the socket open when you call domout.start()

When I go to test it however, domout.log() always fires before the callback for domout.start() returns so the data doesn't get logged.  However, the test case in domout.start() works so everything else is fine.

Any idea how to get this to delay properly?

**Comment by develra** [comment]
Heya, 

Seems like there are couple ways of doing this (and likely a better one I don't know about Ian will provide).
1. (bad) Put some wait condition in domout.log that waits for the domout.start callback (but this is blocking in node, and considered bad practice) (e.g. while(noserver condition) { wait } 
2. (better) in the test file, use the async library's series function (https://github.com/caolan/async#seriestasks-callback)
3. (best) write it to be properly functional, like... 

```
A(function() {
  B(function() {
    C();
  });
});
```

**Comment by ianks** [comment]
Part of me doesn't think that `domout.start` not finishing is your problem. Firstly, there is nothing non-determinstic that function required to make things work. The only things that requires a callback is the `names.on(...)` logic, however that's not necessary for the basics of `domout.log`. The only real thing is `app.listen`, which  is guaranteed to finish before `domout.log` methinks.

I took your code and checked to make sure there was a connection before emitting anything, and it still didn't work... I got confused and gave up lol. Here are some things on first glance that I would prob. check first:
1. Make sure you have same versions of socket.io running on client and server (I noticed they differed)
2. Try using express
3. Check to see that the html is escaped correctly. When rendering clientTemp, I think there are issues with newlines by doing the JS multiline string thing (I would just rip it to a file and use sendFile)

Here is mine, it's pretty similar for the most part modulo a few things mentioned above: https://github.com/sikuli/domout/blob/ianks/index.js

There is another issue that arises with synchronization. That is that case that you have attempted logged some things before the connection has been made by the client. In such case, I think using streams is a wise idea. With streams, as soon as the client connects you can just flush the whole thing. It acts as a queue, almost.

As far as the original question goes: I've recently become a fan of promises. It gives you back all the things you lose with callbacks (i.e. indentation hell, a proper error stream, guaranteed control flows for things like closing databases,  etc). https://github.com/petkaantonov/bluebird/blob/master/API.md

**Comment by wannabeCitizen** [comment]
Thanks for the thoughts guys.  There are definitely too many solutions for this and ultimately all of them count on our final version of the code we are aiming for.

I ended up embedding both the setup function and the normal log as cases of domout.log.  It's janky, but it works on the test cases as expected.

However, @ianks, yours is much cleaner!  However, it doesn't support any test cases yet, but we should just run a few on Weds.  I only  made my template explicitly in the code and everything because I didn't want any hidden stuff for this first prototype.  It seems like we know what to do now so let's just choose a design, assign tasks, and implement it over next week.  We'll chat all this on Weds.
